file:
  path: /home/aagu/IdeaProjects/blog/
server:
  compression:
    enabled: true
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 30000
      connection-test-query: SELECT 1
    password: pwOfBlog
    username: blog
  output:
    ansi:
      enabled: detect
  profiles:
    active: dev
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 10
        max-wait: 1ms
        min-idle: 5
      shutdown-timeout: 100ms
    password: aagu098IsMe36qq8951ace
  resources:
    static-locations: classpath:/static,file:${file.path}
  thymeleaf:
    cache: false
    check-template-location: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html

